import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Accordion from '../components/Accordion'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tiger Streak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <video loop autoPlay muted src="/assets/main-animation.mp4"></video>
      <div className="container">
        <div className="main">
          <div className="mainLeft">
            <div className="hero">
              <h1>NOT YOUR AVERAGE PFP</h1>
              <p>Tiger Streak is a collection of 10,000 utility-enabled Tiger NFTs—unique digital collectibles living on the Ethereum blockchain.</p>
              <p>Your Tiger is the key to the Zoosh Club and grants access to members-only benefits. It starts with exclusive access to our gated Zoosh Discord channels, Tiger Streak drops, IRL events, and access to the Zoosh: our upcoming Web3 AI platform.</p>
              <p>The Streak is a place where ambitious minds and degens alike unite to build on the backbone of art, culture, and community. A Tiger is powerful on its own, but together, the Streak is unstoppable. Our roar will be heard by all.</p>
            </div>
            <div className="aboutContainer">
              <div className="about" style={{marginTop: "40px"}}>
                <div className="about-item">
                  <img className="about-photo" src="/assets/team/alma.png"></img>
                  <h4 className="about-description">10,000 unique Tiger PFPs</h4>
                </div>
                <div className="about-item">
                  <img className="about-photo" src="/assets/team/ironfist.png"></img>
                  <h4 className="about-description">ERC-721A ETH tokens hosted on IPFS</h4>
                </div>
                <div className="about-item">
                  <img className="about-photo" src="/assets/team/niner.png"></img>
                  <h4 className="about-description">Ownership and commercial usage rights given to holders</h4>
                </div>
                <div className="about-item">
                  <img className="about-photo" src="/assets/team/xh121x.png"></img>
                  <h4 className="about-description">Access to The Zoosh Club</h4>
                </div>
                <div className="about-item">
                  <img className="about-photo" src="/assets/team/kronos.png"></img>
                  <h4 className="about-description">Utility NFT</h4>
                </div>
                <div className="about-item">
                  <img className="about-photo" src="/assets/team/kronos.png"></img>
                  <h4 className="about-description">ERC-721A ETH tokens hosted on IPFS</h4>
                </div>
              </div>
            </div>
            <div className="joinStreak">
              <h2>JOIN THE STREAK</h2>
              <button>JOIN THE STREAK</button>
            </div>
            <div className="teamContainer">
              <h2>THE TEAM</h2>
              <div className="team" style={{marginTop: "40px"}}>
                <div className="team-member">
                  <img className="team-photo" src="/assets/team/alma.png"></img>
                  <h2 className="team-member-name">NICK</h2>
                  <h4 className="team-member-title">ZOOSHTER</h4>
                </div>
                <div className="team-member">
                  <img className="team-photo" src="/assets/team/ironfist.png"></img>
                  <h2 className="team-member-name">BEN</h2>
                  <h4 className="team-member-title">ZOOSHTER</h4>
                </div>
                <div className="team-member">
                  <img className="team-photo" src="/assets/team/niner.png"></img>
                  <h2 className="team-member-name">CAETANO</h2>
                  <h4 className="team-member-title">LEAD ARTIST</h4>
                </div>
                <div className="team-member">
                  <img className="team-photo" src="/assets/team/xh121x.png"></img>
                  <h2 className="team-member-name">JULIANNA</h2>
                  <h4 className="team-member-title">DESIGN</h4>
                </div>
                <div className="team-member">
                  <img className="team-photo" src="/assets/team/kronos.png"></img>
                  <h2 className="team-member-name">ROLAND</h2>
                  <h4 className="team-member-title">LEAD DEVELOPER</h4>
                </div>
                <div className="team-member">
                  <img className="team-photo" src="/assets/team/kronos.png"></img>
                  <h2 className="team-member-name">ETHAN</h2>
                  <h4 className="team-member-title">WIZARD</h4>
                </div>
              </div>
            </div>
            <div className="followContainer">
              <h2>FOLLOW THE ZOOSH</h2>
              <div className="follow">
                <a>
                  <img></img>
                  <h3>BLUEPRINT</h3>
                  <p>The Good Stuff</p>
                </a>
                <a>
                  <img></img>
                  <h3>STORY</h3>
                  <p>The Tale of Zoosh</p>
                </a>
                <a>
                  <img></img>
                  <h3>TWITTER</h3>
                  <p>Stay Updated</p>
                </a>
                <a>
                  <img></img>
                  <h3>DISCORD</h3>
                  <p>Zoosh Debauchary</p>
                </a>
              </div>
            </div>
            <div className="faqContainer">
              <div className="faq">
                  <h1>FAQ</h1>
                  <Accordion
                      title="wen mint?"
                      content={`april 27th @ 8 AM PST / 11 AM EST`}
                  />
                  <Accordion
                      title="mint price?"
                      content={`0.18 eth`}
                  />      
                  <Accordion
                      title="what's the max mint?"
                      content={`2 lil frens per wallet.`}
                  />      
                  <Accordion
                      title="why stake?"
                      content={`acquire $fren through staking, spend this brand locked token at our rainbow market place! shop for animations, rare traits, whitelist spots for exclusive projects and much much more.`}
                  />      
                  <Accordion
                      title="why the low supply?"
                      content={`we've personally seen low supply projects greatly outperform high supply and as this is a community first project, it only made sense to have our supply lil at 2,222`}
                  />                  
              </div>
            </div>
          </div>
          <div className="mainRight">
            <img src=""></img>
          </div>
        </div>
      </div>
    </div>
  )
}
